# Weather config
weather.default-query=Zoutleeuw
weather.fallback[0]=Leuven
weather.fallback[1]=Bruxelles
weather.country-code=BE
weather.language=fr
weather.forecast-days=3
weather.timezone=auto
# Open-Meteo URLs
quarkus.rest-client.geocoding-api.url=https://geocoding-api.open-meteo.com/v1
quarkus.rest-client.forecast-api.url=https://api.open-meteo.com/v1
# Cache Caffeine
quarkus.cache.caffeine.geocoding.expire-after-write=7D
quarkus.cache.caffeine.forecast.expire-after-write=15M
weather.cache.geocoding-ttl=7D
weather.cache.forecast-ttl=15M
# Port (équivalent de server.port=8081)
quarkus.http.port=8081
quarkus.http.test-port=8082
# Packaging
quarkus.package.jar.type=uber-jar
# If logging is needed
#quarkus.rest-client.logging.scope=request-response
#quarkus.rest-client.logging.body-limit=1000
#quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG