server {
  port = 8081
}

spring {
  application { name = "weather-service" }
  main { banner-mode = "off" }
  cache { type = "caffeine" }
}

management {
  endpoints {
    web {
      exposure { "include" = ["health", "info"] }
    }
  }
  endpoint {
    health { probes { enabled = true } }
  }
  health {
    livenessstate { enabled = true }
    readinessstate { enabled = true }
  }
}

weather {
  defaultQuery = "3440 Zoutleeuw, BE"
  fallback = ["Leuven, BE", "Bruxelles, BE"]

  countryCode = "BE"
  language = "fr"
  forecastDays = 3
  timezone = "auto"

  cache {
    geocodingTtl = "7d"
    forecastTtl = "15m"
  }

  openMeteo {
    geocodingBaseUrl = "https://geocoding-api.open-meteo.com/v1"
    forecastBaseUrl = "https://api.open-meteo.com/v1"
  }
}