services:
  discord-service:
    image: eclipse-temurin:21-jre-jammy
    container_name: discord-service
    ports:
      - "8766:8081" # port externe modifiable selon l'environnement
    environment:
      - SERVER_PORT=8081
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_ADMIN=${DISCORD_ADMIN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
    volumes:
      - ./discord-0.0.1-SNAPSHOT.jar:/app/app.jar:ro
    command: [ "java","-jar","/app/app.jar" ]
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    external: true